### ISSUE TITLE
AdRotate

### ISSUE THREAD

**Issue by Nikodemsky** [dolatabadi/cleanup-wp-plugins#11]
Plugin Clean Up Request for AdRotate(free):
https://wordpress.org/plugins/adrotate/

A LOT of banners, ads, Pro-only boxes and such:
![1](https://user-images.githubusercontent.com/14090596/32792857-bc65d0f0-c964-11e7-8052-78908dde8f89.png)
![2](https://user-images.githubusercontent.com/14090596/32792858-bc8f57d6-c964-11e7-9dcb-38ac9ae962e0.png)
![3](https://user-images.githubusercontent.com/14090596/32792860-bcb86784-c964-11e7-9a27-655ccfa03bff.png)

**Comment by dolatabadi** [comment]
@Nikodemsky wow that is a lot of ads, I am releasing a new version by the end of the week which includes several other plugins and will add this one as well

**Comment by dolatabadi** [comment]
@Nikodemsky 
I had a chance to look at this plugin and it is a mess. The author used tables to create the ad boxes and did not give unique classes or ids to identify the elements. So it is very difficult to hide those ads. 

The general info page is all ads, there is also a pro menu item in the list, schedules and media are disabled in the normal version.

You should consider using another plugin as this plugin itself is full of ads. Unfortunately clean up this plugin because there is no unique id or class attached to ad boxes.
